package modelo;

public enum Reporte {
        REPORTE1("Se ha robado el collar millenario del antiguo egipto '\n'fue robado el martes pasado y aun no hemos encotrado al culpable'\n'El dichoso objeto esta hecho de oro solido puro '\n'y dotado con los mas finos rubies '\n' esta cotizado en mas de US 100000000'\n''\n'"),
        REPORTE2("asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'"),
        REPORTE3("asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'"),
        REPORTE4("asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'"),
        REPORTE5("asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'"),
        REPORTE6("asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'"),
        REPORTE7("asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'"),
        REPORTE8("asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'"),
        REPORTE9("asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'asflkasjfaksjfaslkfjsalkfasjlkfsajflksajfsalkfjsalkfsa '\n'");

        private String value;

        private Reporte(String value) {
            this.value = value;
        }

        public String getValue() {
            return this.value;
        }
}

